version: '3.9'
services:
  postgres:
    container_name: postgres-container-sp
    build: docker/postgres/.
    restart: always
    env_file:
      - dev.pg.env
    ports:
      - '5432:5432'
    networks:
      - sabbizen_network_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container_sp
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - sabbizen_network_dev
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:

networks:
  sabbizen_network_dev:
    driver: bridge
